apiVersion: v1
kind: Service
metadata:
  name: web-game-service
  namespace: web-game
spec:
  selector:
    app: web-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
